### ISSUE TITLE
Fix Permissions on sample spreadsheets

### ISSUE THREAD

**Issue by bnmnetp** [google/applied-computing-series#84]
We gotta find a way to make the sheets available for editing to non-googlers.

I know you can't just make them public so we'll need to add them on a non-google account and link to them there.

**Comment by jeremyallenjacobson** [comment]
I am teaching with this book using runestone and I need access for myself and students to the many datasets I am finding in the text that require permission to a google drive file.

**Comment by bnmnetp** [comment]
@raskutti we have lost access to the sheets in this book.  how can we get them back?
